import Providers from '@/lib/providers';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Know Me',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers attribute="class" defaultTheme="dark" enableSystem>
        <body className={rubik.className}>{children}</body>
      </Providers>
    </html>
  );
}
