import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Space_Mono } from 'next/font/google';
import Head from 'next/head';
import './globals.css';

const spacemono = Space_Mono({
  weight: ['400'],
  preload: false,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}>
      <html lang="en">
        <Head>
          <title>Know Me</title>
        </Head>
        <body className={spacemono.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
